import './globals.css'
import {Inter} from 'next/font/google'
import Script from "next/Script";
import Header from "@/component/Header";
import Footer from '@/component/Footer';

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    deScription: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>

        <head>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <title>SAILOR</title>
            <link rel="stylesheet" href="./assets/icofont/icofont.min.css"/>
            <link rel="stylesheet" href="./assets/fonts/fonts.css"/>
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
                  integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
                  crossOrigin="anonymous" referrerPolicy="no-referrer"/>
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
            <link rel="stylesheet" href="https://unpkg.com/simplebar@latest/dist/simplebar.css"/>

            <link rel="stylesheet" href="./assets/scss/bootstrap.min.css"/>
            <link rel="stylesheet" href="./assets/scss/style.css"/>
            <link rel="stylesheet" href="./assets/scss/responsive.css"/>
        </head>

        <Header/>
        {children}
        <Footer/>

        <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></Script>
        <Script src="./assets/js/jquery-3.6.1.min.js"></Script>
        <Script src="./assets/js/bootstrap.bundle.min.js"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></Script>
        <Script src="https://unpkg.com/simplebar@latest/dist/simplebar.min.js"></Script>

        <Script src="./assets/js/custom.js"></Script>
        {/*<Script>
            $('.dropdown-toggle , .megamenu').hover(function () {
            $('.dropdown-toggle').toggleClass('show');
            $('.megamenu').toggleClass('show');
        });

        </Script>*/}


        </body>
        </html>
    )
}
